os: osx
language: csharp
install:
    - sudo python2 ./scripts/install-unity.py --package Unity 2017.3.1f1
before_script:
    - sudo chmod -R a+rwx /Applications/Unity
script:
    - ./scripts/build.sh
