os: osx
language: csharp
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
before_script:
    - sudo chmod -R a+rwx /Applications/Unity
